import { MemberWhereUniqueInput } from "../member/MemberWhereUniqueInput";
import { ScheduleWhereUniqueInput } from "../schedule/ScheduleWhereUniqueInput";

export type ScoreUpdateInput = {
  back?: number;
  bhndcp?: number;
  bnet?: number;
  fhndcp?: number;
  firstname?: string;
  fnet?: number;
  front?: number;
  h1?: number;
  h10?: number;
  h11?: number;
  h12?: number;
  h13?: number;
  h14?: number;
  h15?: number;
  h16?: number;
  h17?: number;
  h18?: number;
  h2?: number;
  h3?: number;
  h4?: number;
  h5?: number;
  h6?: number;
  h7?: number;
  h8?: number;
  h9?: number;
  lastname?: string;
  members?: MemberWhereUniqueInput;
  ninePlayed?: string;
  press?: boolean;
  schedule?: ScheduleWhereUniqueInput;
  scoreDate?: Date | null;
};
